version: 2
jobs:
  build:
    machine: true
    working_directory: ~/logs

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build Apache Docker image
          command: |
            cp .env.example .env
            make build
# DEV Build

      - run:
          name: Start DEV Container
          command: |
            set -x
            ls -la
            pwd
            make run
            docker ps -a
            sleep 10
      - run:
          name: Global Environment Vars
          command: |
            docker exec apache /bin/bash -c "export"
      - run:
          name: DEV Build Tests
          command: |
            docker exec apache /bin/bash /opt/tests/build_tests.sh
      - run:
          name: Container Logs
          command: |
            mkdir -p ~/project/container-build
            docker logs apache > ~/project/container-build/log_output-DEV_Apache.txt
            docker logs apache_db > ~/project/container-build/log_output-DEV_MySQL.txt
      - run:
          name: Kill running containers
          command: |
            make stop && make rm
# LIVE Build

      - run:
          name: Start LIVE Container
          command: |
            docker-compose --project-name apache up -d
            docker ps -a
            sleep 10
      - run:d
          name: LIVE Build Tests
          command: |
            docker exec apache_hg-web_1 /bin/bash /opt/tests/build_tests.sh
      - run:
          name: Container Logs
          command: |
            mkdir -p ~/project/container-build
            docker logs apache_hg-web_1 > ~/project/container-build/log_output-LIVE_Apache.txt
            docker logs apache_hg-db_1 > ~/project/container-build/log_output-LIVE_MySQL.txt
      - store_artifacts:
          path: ~/project/container-build
          destination: raw-test-output

      - store_test_results:
          path: ~/project/container-build